name: Check DVC GitHub Action
on: [push]
jobs:
  check:
    strategy:
      matrix:
        os:
          [
            '{"runs-on": "ubuntu-latest"}',
            '{"runs-on": "macos-latest"}',
            '{"runs-on": "ubuntu-latest", "container": "ubuntu:18.04"}',
            '{"runs-on": "windows-latest"}',
          ]
    runs-on: ${{ fromJSON(matrix.os).runs-on }}
    container: ${{ fromJSON(matrix.os).container }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        if: "fromJSON(matrix.os).container == 'ubuntu:18.04'"
        with:
          node-version: '12'
      - uses: actions/setup-python@v2
        if: "contains(fromJSON(matrix.os).runs-on, 'windows')"
        with:
          python-version: '3.x'
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - name: run local action with '1.0.1'
        uses: ./.github/..
        with:
          version: '1.0.1'
      - name: test DVC version
        if: "!contains(fromJSON(matrix.os).runs-on, 'windows')"
        run: |
          DVC_VER=$(dvc --version)
          if [ $DVC_VER != '1.0.1' ]; then
            exit 1
          fi
      - name: run local action with 'latest'
        uses: ./.github/..
        with:
          version: latest
      - name: test DVC version
        if: "!contains(fromJSON(matrix.os).runs-on, 'windows')"
        run: |
          DVC_VER=$(dvc --version)
          if [ $DVC_VER == '1.0.1' ]; then
            exit 1
          fi
